site_name: ThTaxSign


repo_name: dreamptk
repo_url: https://github.com/dreamptk

nav:
  - Home: 'home.md'
  - Get Start: 'get_started.md'
  - YOLOv5: 'yolov5.md'
  - Test: 'index.md'



theme:
  name: material
  logo: img/TH.png
  favicon: img/TH.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en 

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: pink

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        # icon: material/toggle-switch
        icon: material/brightness-4
        name: Switch to light mode    
      primary: deep purple
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DreamPTK
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Godream/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pathakorn-usaha-114283244/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/DreamPTK"  target="_blank" rel="noopener">DreamPTK</a>
